/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRoomsRouteImport } from './routes/app.rooms'
import { Route as AppGuidebookRouteImport } from './routes/app.guidebook'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppBreakfastRouteImport } from './routes/app.breakfast'
import { Route as AppAnnouncementsRouteImport } from './routes/app.announcements'
import { Route as AppAdventuresRouteImport } from './routes/app.adventures'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppTasksTaskIdRouteImport } from './routes/app.tasks.$taskId'
import { Route as AppAdminTemplatesRouteImport } from './routes/app.admin.templates'
import { Route as AppAdminStatsRouteImport } from './routes/app.admin.stats'
import { Route as AppAdminRotaRouteImport } from './routes/app.admin.rota'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoomsRoute = AppRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppGuidebookRoute = AppGuidebookRouteImport.update({
  id: '/guidebook',
  path: '/guidebook',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBreakfastRoute = AppBreakfastRouteImport.update({
  id: '/breakfast',
  path: '/breakfast',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppAdventuresRoute = AppAdventuresRouteImport.update({
  id: '/adventures',
  path: '/adventures',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTemplatesRoute = AppAdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminStatsRoute = AppAdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRotaRoute = AppAdminRotaRouteImport.update({
  id: '/rota',
  path: '/rota',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/adventures': typeof AppAdventuresRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/breakfast': typeof AppBreakfastRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/chat': typeof AppChatRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/guidebook': typeof AppGuidebookRoute
  '/app/rooms': typeof AppRoomsRoute
  '/app/admin/rota': typeof AppAdminRotaRoute
  '/app/admin/stats': typeof AppAdminStatsRoute
  '/app/admin/templates': typeof AppAdminTemplatesRoute
  '/app/tasks/$taskId': typeof AppTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/adventures': typeof AppAdventuresRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/breakfast': typeof AppBreakfastRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/chat': typeof AppChatRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/guidebook': typeof AppGuidebookRoute
  '/app/rooms': typeof AppRoomsRoute
  '/app/admin/rota': typeof AppAdminRotaRoute
  '/app/admin/stats': typeof AppAdminStatsRoute
  '/app/admin/templates': typeof AppAdminTemplatesRoute
  '/app/tasks/$taskId': typeof AppTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/adventures': typeof AppAdventuresRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/breakfast': typeof AppBreakfastRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/chat': typeof AppChatRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/guidebook': typeof AppGuidebookRoute
  '/app/rooms': typeof AppRoomsRoute
  '/app/admin/rota': typeof AppAdminRotaRoute
  '/app/admin/stats': typeof AppAdminStatsRoute
  '/app/admin/templates': typeof AppAdminTemplatesRoute
  '/app/tasks/$taskId': typeof AppTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/admin'
    | '/app/adventures'
    | '/app/announcements'
    | '/app/breakfast'
    | '/app/calendar'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/guidebook'
    | '/app/rooms'
    | '/app/admin/rota'
    | '/app/admin/stats'
    | '/app/admin/templates'
    | '/app/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/admin'
    | '/app/adventures'
    | '/app/announcements'
    | '/app/breakfast'
    | '/app/calendar'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/guidebook'
    | '/app/rooms'
    | '/app/admin/rota'
    | '/app/admin/stats'
    | '/app/admin/templates'
    | '/app/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/admin'
    | '/app/adventures'
    | '/app/announcements'
    | '/app/breakfast'
    | '/app/calendar'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/guidebook'
    | '/app/rooms'
    | '/app/admin/rota'
    | '/app/admin/stats'
    | '/app/admin/templates'
    | '/app/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/rooms': {
      id: '/app/rooms'
      path: '/rooms'
      fullPath: '/app/rooms'
      preLoaderRoute: typeof AppRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/guidebook': {
      id: '/app/guidebook'
      path: '/guidebook'
      fullPath: '/app/guidebook'
      preLoaderRoute: typeof AppGuidebookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/breakfast': {
      id: '/app/breakfast'
      path: '/breakfast'
      fullPath: '/app/breakfast'
      preLoaderRoute: typeof AppBreakfastRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/announcements': {
      id: '/app/announcements'
      path: '/announcements'
      fullPath: '/app/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/adventures': {
      id: '/app/adventures'
      path: '/adventures'
      fullPath: '/app/adventures'
      preLoaderRoute: typeof AppAdventuresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks/$taskId': {
      id: '/app/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/app/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/templates': {
      id: '/app/admin/templates'
      path: '/templates'
      fullPath: '/app/admin/templates'
      preLoaderRoute: typeof AppAdminTemplatesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/stats': {
      id: '/app/admin/stats'
      path: '/stats'
      fullPath: '/app/admin/stats'
      preLoaderRoute: typeof AppAdminStatsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/rota': {
      id: '/app/admin/rota'
      path: '/rota'
      fullPath: '/app/admin/rota'
      preLoaderRoute: typeof AppAdminRotaRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminRotaRoute: typeof AppAdminRotaRoute
  AppAdminStatsRoute: typeof AppAdminStatsRoute
  AppAdminTemplatesRoute: typeof AppAdminTemplatesRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminRotaRoute: AppAdminRotaRoute,
  AppAdminStatsRoute: AppAdminStatsRoute,
  AppAdminTemplatesRoute: AppAdminTemplatesRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAdventuresRoute: typeof AppAdventuresRoute
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppBreakfastRoute: typeof AppBreakfastRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGuidebookRoute: typeof AppGuidebookRoute
  AppRoomsRoute: typeof AppRoomsRoute
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAdventuresRoute: AppAdventuresRoute,
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppBreakfastRoute: AppBreakfastRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGuidebookRoute: AppGuidebookRoute,
  AppRoomsRoute: AppRoomsRoute,
  AppTasksTaskIdRoute: AppTasksTaskIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
